HOST_IP = "localhost"
USER = "root"
PASSWORD = "H@milton2001"
GROUP_NAME = "GroupA"
DEVICE_ID = "DeviceA"

MQTT_HOSTNAME = "nam1.cloud.thethings.network"
MQTT_USERNAME = "4id3-data-collection@ttn"
MQTT_API_KEY = "NNSXS.N2Q47VT6V7IJXGOJPW7LD54QEAR66IEPTBYJLUI.JJNYKQCIO2ZKAJAWKXYILQWBGXAKT7YT4EDF5O3J6MNDJT6IGDVA"
MQTT_PORT = 1883
MQTT_TOPIC = "#"